version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: stacktap
      POSTGRES_PASSWORD: stacktap
      POSTGRES_DB: stacktap
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: