name: Build and Test NestJS

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust the Node.js version if necessary
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Compile the application
      - name: Build Application
        run: yarn build

      # Run tests
      - name: Run Tests
        run: yarn test

      # Optionally check for linting issues
      - name: Run Linter
        run: yarn lint

      # Upload test results (if you use a results formatter)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/ # Adjust the path to your test output

      # Clean up cache if needed
      - name: Cleanup Node Modules
        run: |
          yarn cache clean
          rm -rf node_modules
